apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-application
  namespace: nginx
spec:
  project: default

  source:
    repoURL: https://github.com/billyagasi/argocd-trial.git
    targetRevision: HEAD
    path: nginx
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
